export const CREATE_DIARY_REQUEST = "CREATE_DIARY_REQUEST";
export const CREATE_DIARY_SUCCESS = "CREATE_DIARY_SUCCESS";
export const CREATE_DIARY_ERROR = "CREATE_DIARY_ERROR";
export const CREATE_DIARY_RESET = "CREATE_DIARY_RESET";

export const GET_DIARY_REQUEST = "GET_DIARY_REQUEST";
export const GET_DIARY_SUCCESS = "GET_DIARY_SUCCESS";
export const GET_DIARY_ERROR = "GET_DIARY_ERROR";
export const GET_DIARY_RESET = "GET_DIARY_RESET";
